id: I9431B26B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-15T10:09:56+00:00'
last_modified: '2022-06-14T08:17:40.623324+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6140
  title: མངོན་པ་གོང་མ་དང་འབྲེལ་བའི་སེམས་ཁམས་རིག་པའི་གཞུང་ལུགས།
  author: ''
  base:
    61DB:
      image_group_id: I1KG6207
      title: ''
      total_pages: ''
      order: 1
      base_file: 61DB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
